- name: Include passenger on $PATH
  lineinfile:
    dest=/home/{{ user }}/.bashrc
    state=present
    insertafter=EOF
    line=PATH=$PATH:/opt/passenger/passenger-{{ passenger_version }}/bin

#Do not change folder permission
- name: Create /opt/nginx folder
  file:
    path=/opt/nginx
   owner={{ user }}
    group={{ user }}
    state=directory
  sudo: yes

#Do not change folder permission
- name: Create /opt/passenger folder
  file:
    path=/opt/passenger
    owner={{ user }}
    group={{ user }}
    state=directory
  sudo: yes

- name: Run passenger_install.sh
  script: 
    passenger_install.sh {{ passenger_version }}
    creates=/opt/nginx/conf/nginx.conf

- name: Copying nginx.conf template to /tmp
  template:
    src=nginx.conf.j2
    dest=/opt/nginx/conf/nginx.conf

- name: Create symlink for nginx
  file:
    src=/opt/nginx/sbin/nginx
    dest=/usr/bin/nginx
    state=link
  sudo: yes

- name: Include Nginx on boot
  lineinfile:
    dest=/etc/rc.local
    line=/usr/bin/nginx
  sudo: yes
  notify: start nginx
